#pragma once

enum
{
    PRIMARY_BACKGROUND_COLOR = 1,
    PRIMARY_FOREGROUND_COLOR = 2,
    SECONDARY_BACKGROUND_COLOR = 3,
    SECONDARY_FOREGROUND_COLOR = 4,
    // PER_SECOND_UPDATE = 5,
    ANIMATION_MODE = 6,
};
